// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlMRNUVpLPcJ51hajK8fohDHXuuQy2yA',
    appId: '1:931629371445:web:5caf66741364bbfd13a17c',
    messagingSenderId: '931629371445',
    projectId: 'aplicatiaelevului',
    authDomain: 'aplicatiaelevului.firebaseapp.com',
    storageBucket: 'aplicatiaelevului.firebasestorage.app',
    measurementId: 'G-S2Y0X73YBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsL7J3rI-pCuHH6_WAjyK8c-x_ogcU2yY',
    appId: '1:931629371445:android:63d7387d39e3d37313a17c',
    messagingSenderId: '931629371445',
    projectId: 'aplicatiaelevului',
    storageBucket: 'aplicatiaelevului.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJttQxzj2hQpHhYnmsAPtKPBS9bkhRSU8',
    appId: '1:931629371445:ios:f391c80045659d0513a17c',
    messagingSenderId: '931629371445',
    projectId: 'aplicatiaelevului',
    storageBucket: 'aplicatiaelevului.firebasestorage.app',
    iosBundleId: 'com.example.firster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJttQxzj2hQpHhYnmsAPtKPBS9bkhRSU8',
    appId: '1:931629371445:ios:f391c80045659d0513a17c',
    messagingSenderId: '931629371445',
    projectId: 'aplicatiaelevului',
    storageBucket: 'aplicatiaelevului.firebasestorage.app',
    iosBundleId: 'com.example.firster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWlMRNUVpLPcJ51hajK8fohDHXuuQy2yA',
    appId: '1:931629371445:web:9979d25dde2f995513a17c',
    messagingSenderId: '931629371445',
    projectId: 'aplicatiaelevului',
    authDomain: 'aplicatiaelevului.firebaseapp.com',
    storageBucket: 'aplicatiaelevului.firebasestorage.app',
    measurementId: 'G-Z8RYLDBR12',
  );

}