// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWqx2icOf8dRImzDaSbOlWq-1cPQhiwVM',
    appId: '1:483829433461:web:91d04ebab182b93957e43c',
    messagingSenderId: '483829433461',
    projectId: 'studentid-cd43b',
    authDomain: 'studentid-cd43b.firebaseapp.com',
    storageBucket: 'studentid-cd43b.firebasestorage.app',
    measurementId: 'G-6BFG1DJZ9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMitiJbGwgjip_UE-hGmE1gEbqL2OaXzI',
    appId: '1:483829433461:android:d157ca42a7b0315557e43c',
    messagingSenderId: '483829433461',
    projectId: 'studentid-cd43b',
    storageBucket: 'studentid-cd43b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAfkKwKF7r9yOB0QvHolyy7XsD7p2tCqQ',
    appId: '1:483829433461:ios:074312a0f7af0eee57e43c',
    messagingSenderId: '483829433461',
    projectId: 'studentid-cd43b',
    storageBucket: 'studentid-cd43b.firebasestorage.app',
    iosBundleId: 'com.example.firster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAfkKwKF7r9yOB0QvHolyy7XsD7p2tCqQ',
    appId: '1:483829433461:ios:074312a0f7af0eee57e43c',
    messagingSenderId: '483829433461',
    projectId: 'studentid-cd43b',
    storageBucket: 'studentid-cd43b.firebasestorage.app',
    iosBundleId: 'com.example.firster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWqx2icOf8dRImzDaSbOlWq-1cPQhiwVM',
    appId: '1:483829433461:web:6ce2719ca2838cfe57e43c',
    messagingSenderId: '483829433461',
    projectId: 'studentid-cd43b',
    authDomain: 'studentid-cd43b.firebaseapp.com',
    storageBucket: 'studentid-cd43b.firebasestorage.app',
    measurementId: 'G-F06MCCG30T',
  );
}
